import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { test } from 'node:test';
import { createServer } from 'vite';

const require = createRequire(import.meta.url);
const { validatePdfBase64 } = require('../api/src/lib/agreementSecurity.js');

test('the API accepts a PDF generated by the real volunteer agreement builder', async (t) => {
  const vite = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true },
  });
  t.after(() => vite.close());

  const { buildAgreementPdf } = await vite.ssrLoadModule(
    '/src/app/features/volunteer-agreement/buildAgreementPdf.ts',
  );
  const pdf = await buildAgreementPdf({
    fullName: 'Contract Test Volunteer',
    email: 'volunteer@example.test',
    phone: '0400 000 000',
    startDate: '24 August 2026',
    area: 'Community programs',
    emergencyContact: 'Example Contact, 0400 000 001',
    dietary: 'No preference',
    allergies: 'None',
    signedName: 'Contract Test Volunteer',
    signedDate: '24 August 2026',
    signatureImage:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  });

  assert.equal(validatePdfBase64(pdf.base64).ok, true);
  assert.match(pdf.filename, /^Marra-Volunteer-Agreement-/);
});
